/**
 * S4 — Image upload gate (#141, covers #136 acceptance):
 *   - a batch of synthetic JPEGs lands in ONE series of one study
 *   - at least one real DICOM file uploads successfully
 *
 * Fixtures are generated by tests/e2e/fixtures/generate-fixtures.ts during
 * globalSetup (JPEGs via sharp; the DICOM is built through the repo's own
 * image-to-dicom service).
 */
import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { login, uniq } from './helpers';

test.setTimeout(180_000);

const FIXTURE_DIR = join(__dirname, '.fixtures');
const JPEG_FILES = ['e2e-a.jpg', 'e2e-b.jpg', 'e2e-c.jpg'];

async function postJson(page: import('@playwright/test').APIRequestContext, url: string, headers: Record<string, string>, data: unknown) {
  return page.request.post(url, { headers: { ...headers, 'Content-Type': 'application/json' }, data });
}

test.describe('S4 upload images', () => {
  test('JPEG batch into one series + DICOM upload', async ({ page }) => {
    const authHeaders = await login(page);

    // Arrange: patient + study
    const patientRes = await postJson(page, '/api/patients', authHeaders, {
      mrn: uniq('MRN-E2E-'),
      name: `E2E Upload ${uniq('#')}`,
      gender: 'female',
    });
    expect(patientRes.status()).toBe(201);
    const patient = (await patientRes.json())?.data;

    const studyRes = await postJson(page, '/api/studies', authHeaders, {
      patientId: patient.id,
      studyDate: new Date().toISOString().slice(0, 10),
      modality: 'CF',
      description: 'E2E upload study (#141 S4)',
    });
    expect(studyRes.status()).toBe(201);
    const study = (await studyRes.json())?.data;

    // ── JPEG batch → one series ────────────────────────────────────────────
    let seriesId: string | null = null;
    const jpegImageIds: string[] = [];
    for (let i = 0; i < JPEG_FILES.length; i++) {
      const fileName = JPEG_FILES[i];
      const res = await page.request.post('/api/images/upload', {
        headers: authHeaders,
        multipart: {
          file: {
            name: fileName,
            mimeType: 'image/jpeg',
            buffer: readFileSync(join(FIXTURE_DIR, fileName)),
          },
          studyId: study.id,
          ...(seriesId ? { seriesId } : {}),
          instanceNumber: String(i + 1),
        },
      });
      const text = await res.text();
      expect(res.status(), `upload ${fileName} should succeed: ${text}`).toBe(201);
      const img = JSON.parse(text)?.data;
      expect(img?.id).toBeTruthy();

      if (!seriesId) {
        seriesId = img.seriesId ?? null;
        expect(seriesId, 'first JPEG upload must report its series').toBeTruthy();
      } else {
        expect(img.seriesId ?? seriesId).toBe(seriesId);
      }
      jpegImageIds.push(img.id);
    }
    expect(jpegImageIds.length).toBe(JPEG_FILES.length);

    // All JPEGs are in ONE series of this study
    const seriesRes = await page.request.get(`/api/studies/${study.id}/series`, { headers: authHeaders });
    expect(seriesRes.status()).toBe(200);
    const seriesList = (await seriesRes.json())?.data ?? [];
    const targetSeries = seriesList.find((s: any) => s.id === seriesId);
    expect(targetSeries, 'uploaded series should be listed under the study').toBeTruthy();
    expect(targetSeries.imageCount ?? jpegImageIds.length).toBeGreaterThanOrEqual(JPEG_FILES.length);

    // ── DICOM upload ───────────────────────────────────────────────────────
    const dcmRes = await page.request.post('/api/images/upload-dicom', {
      headers: authHeaders,
      multipart: {
        file: {
          name: 'sample.dcm',
          mimeType: 'application/dicom',
          buffer: readFileSync(join(FIXTURE_DIR, 'sample.dcm')),
        },
      },
    });
    const dcmText = await dcmRes.text();
    expect(dcmRes.status(), `DICOM upload should succeed: ${dcmText}`).toBeLessThan(400);
    const dcmBody = JSON.parse(dcmText);
    expect(dcmBody?.data?.id ?? dcmBody?.data?.imageId, 'DICOM upload must return an image id').toBeTruthy();
  });
});
