/**
 * EnFacePreview — en-face (average projection) preview for OCT volumes.
 *
 * Shows a top-down view of the OCT volume with:
 * - Horizontal line indicating current B-scan position
 * - Click to jump to a specific frame
 *
 * The en-face image is generated by averaging pixel values across
 * all B-scan frames (simplified average projection).
 */

import { useRef, useEffect, useCallback, useState } from 'react';
import { cn } from '@/lib/utils';

interface EnFacePreviewProps {
  /** Slice locations for each frame */
  sliceLocations: number[];
  /** Current frame index (0-based) */
  currentFrame: number;
  /** Total number of frames */
  totalFrames: number;
  /** Callback when user clicks to select a frame */
  onFrameSelect: (index: number) => void;
  /** Width of the preview */
  width?: number;
  /** Height of the preview */
  height?: number;
  className?: string;
}

export function EnFacePreview({
  sliceLocations: _sliceLocations, // used for future slice position display
  currentFrame,
  totalFrames,
  onFrameSelect,
  width = 200,
  height = 120,
  className,
}: EnFacePreviewProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [isHovering, setIsHovering] = useState(false);
  const [hoverFrame, setHoverFrame] = useState(0);

  // Draw the en-face preview
  const draw = useCallback(() => {
    const canvas = canvasRef.current;
    if (!canvas || totalFrames <= 1) return;

    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    canvas.width = width;
    canvas.height = height;

    // Background
    ctx.fillStyle = '#000';
    ctx.fillRect(0, 0, width, height);

    // Draw simulated en-face pattern (vertical stripes representing scan lines)
    // In a real implementation, this would use actual pixel data from the DICOM frames
    const frameWidth = width / totalFrames;

    for (let i = 0; i < totalFrames; i++) {
      const x = i * frameWidth;

      // Generate a gradient based on frame position (simulating tissue reflectivity)
      const intensity = Math.floor(40 + 30 * Math.sin((i / totalFrames) * Math.PI * 3));
      ctx.fillStyle = `rgb(${intensity}, ${intensity}, ${intensity + 20})`;
      ctx.fillRect(x, 0, Math.max(1, frameWidth), height);
    }

    // Draw current frame indicator line
    const indicatorX = (currentFrame / (totalFrames - 1)) * width;
    ctx.strokeStyle = '#00ff00';
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.moveTo(indicatorX, 0);
    ctx.lineTo(indicatorX, height);
    ctx.stroke();

    // Draw hover indicator
    if (isHovering) {
      const hoverX = (hoverFrame / (totalFrames - 1)) * width;
      ctx.strokeStyle = 'rgba(255, 255, 0, 0.5)';
      ctx.lineWidth = 1;
      ctx.setLineDash([4, 4]);
      ctx.beginPath();
      ctx.moveTo(hoverX, 0);
      ctx.lineTo(hoverX, height);
      ctx.stroke();
      ctx.setLineDash([]);
    }

    // Label
    ctx.fillStyle = 'rgba(255, 255, 255, 0.7)';
    ctx.font = '10px sans-serif';
    ctx.fillText('En-face', 4, 12);
  }, [width, height, totalFrames, currentFrame, isHovering, hoverFrame]);

  useEffect(() => {
    draw();
  }, [draw]);

  const handleClick = useCallback((e: React.MouseEvent<HTMLCanvasElement>) => {
    const canvas = canvasRef.current;
    if (!canvas || totalFrames <= 1) return;

    const rect = canvas.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const frame = Math.round((x / width) * (totalFrames - 1));
    onFrameSelect(Math.max(0, Math.min(frame, totalFrames - 1)));
  }, [width, totalFrames, onFrameSelect]);

  const handleMouseMove = useCallback((e: React.MouseEvent<HTMLCanvasElement>) => {
    const canvas = canvasRef.current;
    if (!canvas || totalFrames <= 1) return;

    const rect = canvas.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const frame = Math.round((x / width) * (totalFrames - 1));
    setHoverFrame(Math.max(0, Math.min(frame, totalFrames - 1)));
  }, [width, totalFrames]);

  if (totalFrames <= 1) return null;

  return (
    <div className={cn('border rounded-md overflow-hidden', className)}>
      <canvas
        ref={canvasRef}
        className="cursor-pointer w-full"
        style={{ width, height }}
        onClick={handleClick}
        onMouseMove={handleMouseMove}
        onMouseEnter={() => setIsHovering(true)}
        onMouseLeave={() => setIsHovering(false)}
      />
    </div>
  );
}
